postgres:
  image: eeacms/postgres
  ports:
  - "5432:5432"
  volumes_from:
  - data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DBNAME: datafs zasync
    POSTGRES_DBUSER: zope
    POSTGRES_DBPASS: zope

data:
  image: busybox
  tty: true
  stdin_open: true
  volumes:
  - www-postgres-data:/var/lib/postgresql/data
  - www-postgres-dump:/postgresql.backup
  command: ["chown", "-v", "-R", "999:999", "/var/lib/postgresql/data"]
