postgres:
  image: eeacms/postgres
  ports:
  - "5432:5432"
  volumes_from:
  - data
  env_file:
  - postgres.env

data:
  image: busybox
  volumes:
  - /var/lib/postgresql/data
  - ./conf.d:/postgresql.conf.d:z
  - ./backup:/postgresql.backup:z
  command: chown -R 999:999 /var/lib/postgresql/data
